set nobackup
set number
set t_Co=256
set mouse=a
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set cursorline
set nowrap
set scrolloff=5
set sidescrolloff=30
set textwidth=1000
set laststatus=2
set path+=**
set hlsearch
set wildmenu

syntax on
hi MatchParen ctermbg=Yellow guibg=lightblue
highlight WhitespaceEOL ctermbg=red guibg=Yellow
set visualbell
set colorcolumn=100
set updatetime=100
set virtualedit=block
set autochdir
set exrc
set secure
set relativenumber
set list
set listchars=tab:\|\ ,trail:▫
set ttimeoutlen=0
set notimeout
set viewoptions=cursor,folds,slash,unix
set wrap
set tw=0
set indentexpr=
set foldmethod=indent
set foldlevel=99
set foldenable
set formatoptions-=tc
set splitright
set splitbelow
set noshowmode
set ignorecase
set smartcase
set shortmess+=c
set completeopt=longest,noinsert,menuone,noselect,preview
set lazyredraw
